/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.2/samples
 */

println("corequarkus version : " + libs.versions.corequarkus.get())

val versionTxt = libs.versions.corequarkus.get()

plugins {
    id("java")
}

allprojects {
    group = "my-groupId"
    version = "my-version"
}

val quarkusPlatformGroupId: String by project
val quarkusPlatformArtifactId: String by project
val quarkusPlatformVersion: String by project

dependencies {
    implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
}

subprojects {
    project.version = versionTxt
}