/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.4.2/userguide/multi_project_builds.html
 */

dependencyResolutionManagement {
    repositories.mavenCentral()
    versionCatalogs {
        create("libs") {
            from(files("libs.versions.toml"))
        }
    }
}

pluginManagement {

//    val quarkusPluginVersion: String by settings
//
//    repositories.mavenLocal()
//    repositories.mavenCentral()
    repositories.gradlePluginPortal()
    repositories.mavenCentral()
    plugins {
        id("java-library-conventions") version ("1.0.0-SNAPSHOT")
        id("java-application-conventions") version ("1.0.0-SNAPSHOT")
//        id("io.quarkus") version quarkusPluginVersion
    }
}

rootProject.name = "core-quarkus"

include("core-quarkus-parent")
include("core-quarkus-examples")
include("core-quarkus-parent:platform-quarkus-anonymiser")
findProject(":core-quarkus-parent:platform-quarkus-anonymiser")?.name = "platform-quarkus-anonymiser"
include("core-quarkus-parent:platform-quarkus-anonymiser:platform-quarkus-anonymiser-core")
findProject(":core-quarkus-parent:platform-quarkus-anonymiser:platform-quarkus-anonymiser-core")?.name = "platform-quarkus-anonymiser-core"
include("core-quarkus-parent:platform-quarkus-anonymiser:platform-quarkus-anonymiser-mask")
findProject(":core-quarkus-parent:platform-quarkus-anonymiser:platform-quarkus-anonymiser-mask")?.name = "platform-quarkus-anonymiser-mask"
