/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.4.2/userguide/multi_project_builds.html
 */

dependencyResolutionManagement {
    repositories.mavenCentral()
    versionCatalogs {
        create("libs") {
            from(files("libs.versions.toml"))
        }
    }
}

pluginManagement {
    val quarkusPluginVersion: String by settings
    val quarkusPluginId: String by settings
    repositories {
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }
    plugins {
        id(quarkusPluginId) version quarkusPluginVersion
        id("io.quarkus.extension") version("2.13.2.Final")
        id("java-library-conventions") version ("1.0.0-SNAPSHOT")
        id("java-application-conventions") version ("1.0.0-SNAPSHOT")
    }
}

rootProject.name = "core-quarkus"

include("core-quarkus-examples")
//findProject(":core-quarkus-parent:platform-quarkus-multitenant")?.name = "platform-quarkus-multitenant"
include("core-quarkus-parent:platform-quarkus-multitenant:platform-quarkus-multitenant-rest")
//findProject(":core-quarkus-parent:platform-quarkus-multitenant:platform-quarkus-multitenant-rest")?.name = "platform-quarkus-multitenant-rest"
include("core-quarkus-parent:platform-quarkus-multitenant:platform-quarkus-multitenant-core")
//findProject(":core-quarkus-parent:platform-quarkus-multitenant:platform-quarkus-multitenant-core")?.name = "platform-quarkus-multitenant-core"
//findProject(":core-quarkus-parent:platform-quarkus-context")?.name = "platform-quarkus-context"
include("core-quarkus-parent:platform-quarkus-context:platform-quarkus-request-context")
//findProject(":core-quarkus-parent:platform-quarkus-context:platform-quarkus-request-context")?.name = "platform-quarkus-request-context"
include("core-quarkus-parent:platform-quarkus-anonymiser:platform-quarkus-anonymiser-core")
//findProject(":core-quarkus-parent:platform-quarkus-anonymiser:platform-quarkus-anonymiser-core")?.name = "platform-quarkus-anonymiser-core"
include("core-quarkus-parent:platform-quarkus-anonymiser:platform-quarkus-anonymiser-mask")
//findProject(":core-quarkus-parent:platform-quarkus-anonymiser:platform-quarkus-anonymiser-mask")?.name = "platform-quarkus-anonymiser-mask"
include("core-quarkus-parent:platform-quarkus-anonymiser:platform-quarkus-anonymiser-mask:runtime")
//findProject(":core-quarkus-parent:platform-quarkus-anonymiser:platform-quarkus-anonymiser-mask:runtime")?.name = "runtime"
include("core-quarkus-parent:platform-quarkus-anonymiser:platform-quarkus-anonymiser-mask:deployment")
//findProject(":core-quarkus-parent:platform-quarkus-anonymiser:platform-quarkus-anonymiser-mask:deployment")?.name = "deployment"
include("core-quarkus-parent:platform-quarkus-anonymiser:platform-quarkus-anonymiser-mask:tests")
//findProject(":core-quarkus-parent:platform-quarkus-anonymiser:platform-quarkus-anonymiser-mask:tests")?.name = "tests"
